### ISSUE TITLE
Java exception when running particular json outputs

### ISSUE THREAD

**Issue by danbuckland** [MagenTys/donut#14]
When running Donut directly from terminal using `java -jar donut-0.0.3-one-jar.jar -s .` I sometimes receive an error that prevents the report from being generated. This has been reproduced with many different feature files of varying formats and complexities and I can't spot any obvious pattern. 

I have now managed to pin it down to two scenarios, when I run scenario 1, it passes and I can successfully generate a Donut report with the JSON output (**test1.json**). When I run scenario 2, it also passes and I can successfully generate a Donut report with that JSON output (**test2.json**). However, if I run scenario 1 and 2 as part of the same test run, attempting to use Donut with that JSON output (**test1andtest2.json**) throws the following error:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.simontuffs.onejar.Boot.run(Boot.java:340)
    at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.IndexOutOfBoundsException: 0
    at scala.collection.LinearSeqOptimized$class.apply(LinearSeqOptimized.scala:65)
    at scala.collection.immutable.List.apply(List.scala:84)
    at io.magentys.donut.transformers.cucumber.CucumberTransformer$$anonfun$mapToDonutScenarios$1.apply(CucumberTransformer.scala:55)
    at io.magentys.donut.transformers.cucumber.CucumberTransformer$$anonfun$mapToDonutScenarios$1.apply(CucumberTransformer.scala:53)
    at scala.collection.immutable.List.flatMap(List.scala:327)
    at io.magentys.donut.transformers.cucumber.CucumberTransformer$.mapToDonutScenarios(CucumberTransformer.scala:53)
    at io.magentys.donut.transformers.cucumber.CucumberTransformer$.mapToDonutFeature(CucumberTransformer.scala:30)
    at io.magentys.donut.transformers.cucumber.CucumberTransformer$$anonfun$mapToDonutFeatures$1.apply(CucumberTransformer.scala:24)
    at io.magentys.donut.transformers.cucumber.CucumberTransformer$$anonfun$mapToDonutFeatures$1.apply(CucumberTransformer.scala:21)
    at scala.collection.immutable.List.map(List.scala:273)
    at io.magentys.donut.transformers.cucumber.CucumberTransformer$.mapToDonutFeatures(CucumberTransformer.scala:21)
    at io.magentys.donut.transformers.cucumber.CucumberTransformer$.transform(CucumberTransformer.scala:12)
    at io.magentys.donut.gherkin.Generator$$anonfun$3.apply(Generator.scala:61)
    at io.magentys.donut.gherkin.Generator$$anonfun$3.apply(Generator.scala:59)
    at io.magentys.donut.performance.PerformanceSupport$class.timed(PerformanceSupport.scala:13)
    at io.magentys.donut.gherkin.Generator$.timed(Generator.scala:15)
    at io.magentys.donut.gherkin.Generator$.createReport(Generator.scala:59)
    at io.magentys.donut.gherkin.Generator$.apply(Generator.scala:32)
    at io.magentys.donut.Boot$.delayedEndpoint$io$magentys$donut$Boot$1(Boot.scala:82)
    at io.magentys.donut.Boot$delayedInit$body.apply(Boot.scala:11)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.App$class.main(App.scala:76)
    at io.magentys.donut.Boot$.main(Boot.scala:11)
    at io.magentys.donut.Boot.main(Boot.scala)
    ... 6 more
```

I have attached the respective JSON files for reference. Possibly I'm missing something obvious or doing something wrong when running but this seems to be quite common across our projects.

[JSONOutputs.zip](https://github.com/MagenTys/donut/files/536028/JSONOutputs.zip)

**Comment by MagenTysHamo** [comment]
thanks @danbuckland, we will take a look

**Comment by Hamo69** [comment]
I think this can be closed @amitsha ?

**Comment by amitsha** [comment]
I can replicate the issue even with the latest code. Investigating to find out what's wrong.

**Comment by amitsha** [comment]
The combined json is missing a background element for the 2nd scenario.
[test1andtest2.json.zip](https://github.com/MagenTys/donut/files/1370539/test1andtest2.json.zip)
I've fixed the json file to have a background element.

The error message does need improvement though.
